repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/bjd2385/circleci-orb-pre-commit-hook
    rev: v1.0.1
    hooks:
      - id: circleci-orb-validate
        args:
          - src

  - repo: https://github.com/hqoapp/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: add-msg-issue-prefix
        stages: [prepare-commit-msg]
