description: base default CircleCI executor.
docker:
  - image: 'cimg/base:<< parameters.tag >>'
parameters:
  tag:
    default: stable-20.04
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
